name: Bug Report
description: "Issues with digsite content: e.g missing assets, incorrect animations, misnamed tags."
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: "## MCC Halo Editing Kit Issue Form"
- type: dropdown
  id: toolkit
  attributes:
    label: "Game"
    description: Which game is the content for?
    options:
      - Halo 1
      - Halo 2
      - Halo 3
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Issue description
    description: Describe the issue in detail. If this is a visual issue include screenshots or videos.
  validations:
    required: true
- type: textarea
  id: reproduction-steps
  attributes:
    label: Reproduction steps
    description: Write steps on how to reproduce the issue. Please include as much detail as you can. 
  validations:
    required: true
- type: textarea
  id: debug_logs
  attributes:
    label: Debug logs
    description: Please upload `crash_info.txt` and `debug.txt` here if possible. **Note these files can include your computer and username so if that's a concern you can edit them to redact that information.**
  validations:
    required: false
- type: dropdown
  id: repro-success
  attributes:
    label: How often does the issue occur?
    description: When attempting to reproduce the issue, how often are you successful?
    options:
      - Once
      - 25%
      - 50%
      - 75%
      - 100%
  validations:
    required: true
- type: textarea
  id: comments
  attributes:
    label: Additional comments
    description: Write any additional comments you have here.
  validations:
    required: false
